// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	KEY_CACHE: KVNamespace;
	AUTH_SECRET: "Fg/niV5ZRRturknJHLISW1SiUl1MtVeY1vmFGHMdAmg=";
	RESEND_API_KEY: "re_Sx1ZeQ8a_LcNAVqPkFBe1CULxZ75YtrYk";
	DB: D1Database;
	ASSETS: Fetcher;
}
